# deps_raw.txt — FROZEN SNAPSHOT dated 2026-07-20. Not regenerable.
#
# 墓碑：本文件原本自称「generated by cmd/pkganalyze」，那是个幻影 —— 该命令从未
# 存在过（`git log --all -- cmd/pkganalyze` 零输出），仓库里也没有任何工具输出
# 下面这个格式。最接近的活工具是 `cmd/depsanalyze`，但它打的是定宽列
# （`<package> <files> <lines> [deps]`），不是这里的 `key=value` 形状，所以
# 「重跑生成器」这条路对本文件不成立。
#
# 因此：下面的数字是 2026-07-20 那一刻的记录，此后只会越来越旧，任何人都不该
# 拿它当当期事实用。要当期依赖数据请跑 `go run ./cmd/depsanalyze`。
# 本文件与仓库根的另外几个历史产物一并计划在 W10/CONTRIB1 删除。
#
# Format: <package> files=<N> lines=<N> deps=[<comma-separated>]

internal/acp                                  files=7   lines=1519    deps=[guard]
internal/agent/goalloop                       files=11  lines=1660    deps=[acp, guard, vcs]
internal/agent/orchestrator                   files=4   lines=1449    deps=[guard, llm/eino, proto, tools]
internal/agent/registry                       files=2   lines=90      deps=[guard]
internal/agent/worker                         files=2   lines=404     deps=[guard, store]
internal/api/http                             files=7   lines=2232    deps=[agent/orchestrator, ctxcompact, guard, llm/eino, proto, skills, store, task, tools]
internal/bootstrap                            files=1   lines=368     deps=[agent/orchestrator, api/http, config, guard, instruct, llm/eino, skills, store, task, tools, vcs]
internal/cli                                  files=9   lines=1697    deps=[acp, bootstrap, config, lockfile, proto, store]
internal/cli/tui                              files=12  lines=5126    deps=[cli, ctxcompact, guard, proto, version]
internal/config                               files=1   lines=152     deps=[guard]
internal/ctxcompact                           files=11  lines=947     deps=[(none)]
internal/guard                                files=4   lines=400     deps=[(none)]
internal/instruct                             files=1   lines=160     deps=[(none)]
internal/llm                                  files=2   lines=141     deps=[(none)]
internal/llm/eino                             files=9   lines=2642    deps=[config, ctxcompact]
internal/lockfile                             files=2   lines=205     deps=[(none)]
internal/plugin                               files=1   lines=50      deps=[(none)]
internal/proto                                files=1   lines=399     deps=[(none)]
internal/skills                               files=2   lines=239     deps=[(none)]
internal/store                                files=6   lines=848     deps=[(none)]
internal/task                                 files=1   lines=246     deps=[store, vcs]
internal/tools                                files=21  lines=4645    deps=[guard, instruct, proto, skills, store, vcs]
internal/vcs                                  files=2   lines=1086    deps=[guard, store]
internal/vcs/mcp                              files=1   lines=456     deps=[vcs]
internal/version                              files=1   lines=5       deps=[(none)]
