// Code generated by cmd/api-schema; DO NOT EDIT.
// Yanshi Agent API v1 — TypeScript contract mirror of internal/api/v1/types.go.
// D1-DEC-2 option A: built-in Go generator (no Node/npm dependency).

export type AgentApiVersion = "v1";

export type ItemType =
  | "turn.started"
  | "message.delta"
  | "reasoning.delta"
  | "tool.call"
  | "tool.result"
  | "tool.progress"
  | "structured.result"
  | "turn.error"
  | "turn.completed";

export interface Thread {
  version: AgentApiVersion;
  id: string;
  status: string;
  title?: string;
  createdAt: number;
  updatedAt: number;
  model?: string;
  thinking?: string;
  turns?: Turn[];
}

export interface Turn {
  version: AgentApiVersion;
  id: string;
  threadId: string;
  status: string;
  input: string;
  startedAt: number;
  completedAt?: number;
}

export interface Item {
  version: AgentApiVersion;
  id: string;
  sequence: number;
  threadId: string;
  turnId: string;
  type: ItemType | `event.${string}`;
  text?: string;
  toolName?: string;
  toolArgs?: string;
  status?: string;
  error?: string;
  structuredResult?: unknown;
}

export interface ThreadStartParams {
  version?: AgentApiVersion;
  title?: string;
  model?: string;
  thinking?: string;
}

export interface ThreadResumeParams {
  version?: AgentApiVersion;
  threadId: string;
}

export interface ThreadInterruptParams {
  version?: AgentApiVersion;
  threadId: string;
  turnId?: string;
}

export interface TurnStartParams {
  version?: AgentApiVersion;
  threadId: string;
  input: string;
  model?: string;
  thinking?: string;
  outputSchema?: unknown;
}

export interface ThreadStartResponse {
  version: AgentApiVersion;
  thread: Thread;
}

export interface ThreadResumeResponse {
  version: AgentApiVersion;
  thread: Thread;
  items?: Item[];
}

export interface TurnStartResponse {
  version: AgentApiVersion;
  turn: Turn;
}

export interface InterruptResponse {
  version: AgentApiVersion;
  ok: boolean;
  threadId: string;
  turnId?: string;
}

export interface ItemUpdatedNotification {
  jsonrpc: "2.0";
  method: "item/updated";
  params: Item;
}

export interface Capabilities {
  version: AgentApiVersion;
  methods: string[];
  itemTypes: string[];
  unknownFields: "ignored";
  stream: "item/updated";
}
