// Package main is cmd/api-schema: the Yanshi Agent API v1 TypeScript
// generator. It reads the canonical JSON Schema from internal/api/v1.SchemaBytes
// and emits TypeScript definitions with no external Node/npm dependency (per
// D1-DEC-2 option A: Go built-in generator).
//
// Usage:
//
//	go run ./cmd/api-schema              # write to stdout
//	go run ./cmd/api-schema -out sdk/ts/v1.ts
//
// The generated file mirrors the Go struct tags in internal/api/v1/types.go.
// Both must be updated together when the wire contract changes; the schema
// tests in internal/api/v1 enforce the camelCase key contract on the Go side.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/x6nux/yanshi/internal/api/v1"
)

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

// run is the testable entry point: it parses args and dispatches the generator
// modes, returning the process exit code. main is a thin wrapper so the flag
// parsing and mode branching can be exercised without spawning a subprocess.
func run(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("api-schema", flag.ContinueOnError)
	fs.SetOutput(stderr)
	outPath := fs.String("out", "", "write TypeScript output to this file; empty means stdout")
	markdownPath := fs.String("markdown", "", "write generated markdown blocks to this file (schema doc or resources table source)")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	if *outPath != "" && *markdownPath != "" {
		fmt.Fprintln(stderr, "cmd/api-schema: -out and -markdown are mutually exclusive")
		return 2
	}

	if *markdownPath != "" {
		if err := runMarkdown(*markdownPath); err != nil {
			fmt.Fprintln(stderr, err)
			return 1
		}
		return 0
	}

	text := `// Code generated by cmd/api-schema; DO NOT EDIT.
// Yanshi Agent API v1 — TypeScript contract mirror of internal/api/v1/types.go.
// D1-DEC-2 option A: built-in Go generator (no Node/npm dependency).

export type AgentApiVersion = "v1";

export type ItemType =
  | "turn.started"
  | "message.delta"
  | "reasoning.delta"
  | "tool.call"
  | "tool.result"
  | "tool.progress"
  | "structured.result"
  | "turn.error"
  | "turn.completed";

export interface Thread {
  version: AgentApiVersion;
  id: string;
  status: string;
  title?: string;
  createdAt: number;
  updatedAt: number;
  model?: string;
  thinking?: string;
  turns?: Turn[];
}

export interface Turn {
  version: AgentApiVersion;
  id: string;
  threadId: string;
  status: string;
  input: string;
  startedAt: number;
  completedAt?: number;
}

export interface Item {
  version: AgentApiVersion;
  id: string;
  sequence: number;
  threadId: string;
  turnId: string;
  type: ItemType | ` + "`event.${string}`" + `;
  text?: string;
  toolName?: string;
  toolArgs?: string;
  status?: string;
  error?: string;
  structuredResult?: unknown;
}

export interface ThreadStartParams {
  version?: AgentApiVersion;
  title?: string;
  model?: string;
  thinking?: string;
}

export interface ThreadResumeParams {
  version?: AgentApiVersion;
  threadId: string;
}

export interface ThreadInterruptParams {
  version?: AgentApiVersion;
  threadId: string;
  turnId?: string;
}

export interface TurnStartParams {
  version?: AgentApiVersion;
  threadId: string;
  input: string;
  model?: string;
  thinking?: string;
  outputSchema?: unknown;
}

export interface ThreadStartResponse {
  version: AgentApiVersion;
  thread: Thread;
}

export interface ThreadResumeResponse {
  version: AgentApiVersion;
  thread: Thread;
  items?: Item[];
}

export interface TurnStartResponse {
  version: AgentApiVersion;
  turn: Turn;
}

export interface InterruptResponse {
  version: AgentApiVersion;
  ok: boolean;
  threadId: string;
  turnId?: string;
}

export interface ItemUpdatedNotification {
  jsonrpc: "2.0";
  method: "item/updated";
  params: Item;
}

export interface Capabilities {
  version: AgentApiVersion;
  methods: string[];
  itemTypes: string[];
  unknownFields: "ignored";
  stream: "item/updated";
}
`

	// Smoke check: re-encode the Go schema document to make sure cmd/api-schema
	// stays in sync with internal/api/v1.SchemaBytes. The bytes are not embedded
	// in the TypeScript output (TS gets the hand-maintained interfaces above so
	// the types stay readable), but the call guards the generator against silent
	// drift if the Go schema ever moves.
	_ = v1.SchemaBytes()

	if *outPath == "" {
		fmt.Fprint(stdout, text)
		return 0
	}
	if err := os.WriteFile(*outPath, []byte(text), 0o644); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}
